modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="marvel_mashup"
version="1.0.0"
displayName="Marvel Mashup"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tobyd, MCreator"

[[dependencies.marvel_mashup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




